## Задание по библиотекам NumPy
### Лабораторная работа № 4 по дисциплине "Технологии программирования"

Подключаем необходимые библиотеки:

In [1]:
import numpy as np
import pandas as pd
import sklearn

## Индивидуальное задание
Вариант 5

## Функция f = p * Tr(q * vT) 

Создадим квадратичные матрицы M и N из 85 элементов

In [25]:
# Размер матрицы
size = 85

# Создаем матрицу, заполненную 2 по всему массиву
M = 2 * np.ones((size, size), dtype=int)

# Заполняем главную диагональ числом арифметической прогрессией с шагом от 3 до 171 с шагом 3
np.fill_diagonal(M, np.arange(3, 173, 2))

print("Matrix M\n", M)

# Создаем матрицу, заполненную 4 по всему массиву
N = 4 * np.ones((size, size), dtype=int)
# Заполняем каждую нечетную строку числом 5 после каждого второго элемента
N[0::2, 2::3] = 5
# Заполняем каждую четную строку числом 7 после каждого элемента
N[1::2, 1::2] = 7

print("Matrix N\n", N)


Matrix M
 [[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]
Matrix N
 [[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]


Вектор нормального распределения с математическим ожиданием a=2 и дисперсией σ2=4

In [32]:
mean = 2 # математическое ожидание
sigma_squared = 4 # дисперсия 
std_dev = np.sqrt(sigma_squared) # стандартное отклонение

# Генерируем массив чисел, распределенных нормально
p = np.random.normal(loc=mean, scale=std_dev, size=(85,))

print('Vector p\n', p)


Vector p
 [ 3.63765142  4.84588908  1.1497204  -1.3664251  -2.31441029  2.83476323
  2.10474623  3.27395662  2.10563636  2.04718614  4.43496764  3.95171287
 -1.32245447  3.28035051  3.18196056  0.03748763  1.87942191  2.08224146
  0.04699012  0.57047016  4.61058472  2.69978391  1.7573545  -2.27577906
  3.85105034  0.57721599  5.964899    2.73655262 -1.5831795  -1.23466141
  2.54574141 -2.72321921  2.1795828   0.6854622   2.98224786  3.48603174
 -0.70253784  4.23630031  4.43264031  3.10022215  0.54033603  4.4882694
  1.22933069  0.99379568 -0.02120667  0.33397922  2.49720569  0.18978771
 -1.5611348   0.4073827  -0.13309384  3.91226857  2.61788796  4.60941625
  2.65739396 -0.51665269  1.81894732  2.88690364 -2.0828209   5.37751006
 -0.73833977  4.53126727  2.81220884  5.82799955 -1.06411219  4.1908874
 -0.92593013  0.99163433  1.9735003   0.76233881  1.49446185  0.75842914
  2.66859026  3.82238914  2.50415834  5.00720627  0.83716013  2.8626744
  0.190479    3.44528946  1.54204538 -1.6127

Транспонированный вектор q

In [55]:
# Выполняем поэлементное умножение нужных строк из матриц N и M с изменением каждого элемента j на 1
q = N[24][:] * M[71][:]

# Транспонирование вектора
qT = q.reshape(-1, 1)

print(qT)

[[  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [725]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]
 [  8]
 [ 10]
 [  8]]


Транспонированный вектор v

In [67]:
i = np.arange(85)
v = M[84-i] + 2*N[i]

# Транспонирование вектора
vT = v.reshape(-1, 1)

print(vT)

[[10]
 [10]
 [12]
 ...
 [10]
 [12]
 [10]]


След произведения векторов q и vT

In [69]:
trace_matrix = np.trace(q*vT)
print(trace_matrix)

17852


Значение функции f = p * Tr(q * vT) 

In [71]:
f = p * trace_matrix
print(f)

[ 54.56477128  72.68833625  17.24580599 -20.49637643 -34.71615442
  42.5214485   31.5711934   49.10934928  31.58454534  30.70779207
  66.52451457  59.27569308 -19.836817    49.20525769  47.72940844
   0.56231438  28.19132861  31.23362194   0.70485175   8.55705237
  69.15877081  40.49675872  26.36031757 -34.13668589  57.76575504
   8.65823982  89.47348493  41.04828928 -23.7476925  -18.51992119
  38.18612108 -40.84828821  32.69374201  10.28193297  44.73371788
  52.29047614 -10.53806759  63.54450467  66.48960464  46.50333228
   8.10504049  67.32404107  18.43996031  14.9069352   -0.31810001
   5.00968832  37.45808541   2.8468156  -23.41702193   6.11074047
  -1.99640764  58.68402861  39.26831947  69.14124369  39.86090947
  -7.74979029  27.28420976  43.30355454 -31.2423135   80.66265097
 -11.07509658  67.96900909  42.18313263  87.41999324 -15.96168278
  62.86331095 -13.88895191  14.87451501  29.60250452  11.43508213
  22.41692781  11.37643707  40.02885391  57.33583709  37.56237506
  75.10809

## Функция g = || qT * N ||_1

In [73]:
#L1-норма
l1_norm = np.linalg.norm(qT*N, ord=1)
print(l1_norm)

9413.0
